Algoritmo "semnome"
// Disciplina   : [Nivelamento em Programação de Computadores]
// Professor   : Alexandra Lackmann Zimpeck
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tatiana Weska
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
inteiro: A, B, C;
caracter: mens;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo